### ISSUE TITLE
Windows builds crash on load/save dialog

### ISSUE THREAD

**Issue by vcaputo** [emoon/rocket#168]
I've been building Win32 versions w/mingw for my musician to start testing the multi-client changes w/schism and everything I've been working on, but he reported that RocketEditor would just crash when trying to load or save tracks.

Looking at the code, it seems like maybe this has never worked?  Are we completely off the reservation here with trying to use the editor in Windows?

The windows implementation of Dialog_open() expects a path_size argument, but none of the Dialog_open() call sites actually supply one:

https://github.com/emoon/rocket/blob/master/src/windows/Dialogs.c#L7

https://github.com/emoon/rocket/blob/master/src/loadsave.c#L258

https://github.com/emoon/rocket/blob/master/src/Editor.c#L916

It's a trivial matter to wire up the path sizes everywhere, and that seems to fix it in my testing under WINE.  I'll post a PR once the dust settles a bit over here, just wanted to note the issue for now.

**Comment by emoon** [comment]
I know a bunch of people that use the Windows version and saving / loading works fine, but this code looks totally broken for sure. I'm not sure why there aren't any warnings in the code about it.

The correct fix here is to supply the path size from the call site for sure so a fix for that would be great!

Related to paths this is something I want to be done also https://github.com/emoon/rocket/issues/123 because now non-ASCII will not work correctly either on Windows.

**Comment by vcaputo** [comment]
@emoon minimally fixed by https://github.com/emoon/rocket/issues/168#issuecomment-1644255413

ptal
